#!/bin/bash
source "lum.l"; STARTLUMFRAMEWORK

Class test {
        $..server() {
                echo "Content-Type: text/html"
                echo "testcook=$GET_cook;"
                echo "200"


                if ( "$http_location" == "/html" ) {
                        $..html;
                } else if ( "$http_location" == "/test" ) {
                        set;
                } else {
                        echo "is a bash http server!";
                }i
        }f

        $..html() {
                cat html;
        }f

}c


HOST=localhost PORT=8081 http_server test;
