#!/bin/bash
source "lum.l"; STARTLUMFRAMEWORK

Class test {
        $..server() {
                echo "Content-Type: text/html"
                echo ""
                echo "200"
				
				declare -A obj;

				lum.json.decode obj < test.json;

				obj[key1]="key 1 value";

				lum.json.encode obj;

        }f


}c

HOST=localhost PORT=8080 lum.http.server test;
